### ISSUE TITLE
Value Error: Traceback (most recent call last) for line: xhat = inv_model.invert(y=rrs, x=x0)

### ISSUE THREAD

**Issue by mkoenig3** [tadz-io/hydropt#2]
Hi again,

the code is now running except for the last line:

`xhat = inv_model.invert(y=rrs, x=x0)`

Here, I receive the following:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_3728\1455539996.py in <module>
      4     minimizer=lmfit.minimize)
      5 # estimate parameters
----> 6 xhat = inv_model.invert(y=rrs, x=x0)

~\Anaconda3\envs\CarbonMapper_py3713\lib\site-packages\hydropt\hydropt.py in invert(self, y, x, w, jac, **kwargs)
    275         args = self._band_model((y, self._fwd_model.forward))
    276         # do optimization
--> 277         xhat = self._minimizer(loss_fun, x, args=args, Dfun=jac_fun, **kwargs)
    278         # warnings.warn('''no band transformation is applied to jacobian -
    279         #  o.k. when band_model = 'rrs' ''')

~\Anaconda3\envs\CarbonMapper_py3713\lib\site-packages\lmfit\minimizer.py in minimize(fcn, params, method, args, kws, iter_cb, scale_covar, nan_policy, reduce_fcn, calc_covar, max_nfev, **fit_kws)
   2581                        nan_policy=nan_policy, reduce_fcn=reduce_fcn,
   2582                        calc_covar=calc_covar, max_nfev=max_nfev, **fit_kws)
-> 2583     return fitter.minimize(method=method)

~\Anaconda3\envs\CarbonMapper_py3713\lib\site-packages\lmfit\minimizer.py in minimize(self, method, params, **kws)
   2350                         val.lower().startswith(user_method)):
   2351                     kwargs['method'] = val
-> 2352         return function(**kwargs)
   2353 
   2354 

~\Anaconda3\envs\CarbonMapper_py3713\lib\site-packages\lmfit\minimizer.py in leastsq(self, params, max_nfev, **kws)
   1687         result.call_kws = lskws
   1688         try:
-> 1689             lsout = scipy_leastsq(self.__residual, variables, **lskws)
   1690         except AbortFitException:
   1691             pass

~\Anaconda3\envs\CarbonMapper_py3713\lib\site-packages\scipy\optimize\minpack.py in leastsq(func, x0, args, Dfun, full_output, col_deriv, ftol, xtol, gtol, maxfev, epsfcn, factor, diag)
    422             maxfev = 200*(n + 1)
    423         retval = _minpack._lmdif(func, x0, args, full_output, ftol, xtol,
--> 424                                  gtol, maxfev, epsfcn, factor, diag)
    425     else:
    426         if col_deriv:

~\Anaconda3\envs\CarbonMapper_py3713\lib\site-packages\lmfit\minimizer.py in __residual(self, fvars, apply_bounds_transformation)
    600         else:
    601             return _nan_policy(np.asarray(out).ravel(),
--> 602                                nan_policy=self.nan_policy)
    603 
    604     def __jacobian(self, fvars):

~\Anaconda3\envs\CarbonMapper_py3713\lib\site-packages\lmfit\minimizer.py in _nan_policy(arr, nan_policy, handle_inf)
   2434                    'handle this! Please read https://lmfit.github.io/lmfit-py/faq.html#i-get-errors-from-nan-in-my-fit-what-can-i-do '
   2435                    'for more information.')
-> 2436             raise ValueError(msg)
   2437     return arr
   2438 

ValueError: NaN values detected in your input data or the output of your objective/model function - fitting algorithms cannot handle this! Please read https://lmfit.github.io/lmfit-py/faq.html#i-get-errors-from-nan-in-my-fit-what-can-i-do for more information.`

Any thoughts?

Thanks and best regards,
Marcel

**Comment by tadz-io** [comment]
Hi Marcel,

My first guess would be that you have NaN values in the spectrum you are trying to invert. Can you confirm?

**Comment by mkoenig3** [comment]
Hi Tadzio,

I took a look and there are no NaN values in the spectrum. It is the `rrs` computed with the forward model.
I noticed that it is only a single array without wavelength information. Could this be the reason?

**Comment by tadz-io** [comment]
> Hi Tordzio,
> 
> I took a look and there are no NaN values in the spectrum. It is the `rrs` computed with the forward model. I noticed that it is only a single array without wavelength information. Could this be the reason?

The forward model only returns a 1d array with the reflectance at each waveband. Indeed, the wavelength of each band is not returned. It's on my to do list... Can you show me a code snippet of how you defined your bio-optics, forward and inverse model? 

Cheers,

Tadzio

**Comment by mkoenig3** [comment]
I really only just followed the _Getting Started_ guide on your Github (https://github.com/tadz-io/hydropt) ;)

Cheers and many thanks!!
Marcel

**Comment by tadz-io** [comment]
I see. HYDROPT can not deal with negative or zero values (due to log-transformations). So you should set a lower bound on your retrieval parameters that is greater than zero. I forgot to mention that in the readme. Will update it asap. Thanks for reaching out!

So set your optimisation parameters like this:

```python
x0 = lmfit.Parameters()
# some initial guess
x0.add('phyto', value=.5,  min=1E-9)
x0.add('cdom', value=.01, min=1E-9)
```

**Comment by mkoenig3** [comment]
Wow, thanks for the quick solution :)
Again, keep up the good work and probably talk to you soon again ;)

Cheers,
Marcel

**Comment by tadz-io** [comment]
glad to help! Do you have an email address i can contact you on? I have been following CarbonMapper for a while and would be curious to know what you are working on :)

Cheers,

Tadzio

**Comment by mkoenig3** [comment]
Sure! You can reach me at ***@***.***
I have only started on CarbonMapper very recently but water quality is one
focus :)

Cheers,
Marcel
