### ISSUE TITLE
#Issue with lmfit minimizer() 

### ISSUE THREAD

**Issue by punyaravichandran** [tadz-io/hydropt#4]
Couldn't map the Xarray data array using inversionmodel.invert function 

Getting an Attribute error: 'MinimizerResult' has no attribute 'dims'

**Comment by tadz-io** [comment]
@punyaravichandran thanks for reporting. Judging from your email you are trying to invert a sentinel 3 scene. The `InversionModel` class has a `invert_scene` method that you can use to invert satellite scenes:

https://github.com/tadz-io/hydropt/blob/c9dca3a2ed6b4eb1e59deb08fd2891d716b739ef/hydropt/hydropt.py#L282

In your case you can apply it like this:

`
y_hat = inv_model.invert_scene(y=ds.rrs, x=x0, axes=0)
`

Here i assume the first axes is the spectral dimension (`axes=0`) and the other two dimensions are the spatial dimensions of your cube. Change the axes argument for the axis corresponding to your spectral dimension

**Comment by tadz-io** [comment]
@punyaravichandran is the issue solved? Can i close this issue?

**Comment by punyaravichandran** [comment]
Thank you so much Tadzio. The issue is solved. You can close the issue.
Many thanks
Punya. P
