### ISSUE TITLE
question about the inversion process for absorption coefficient a and backscatter coefficient b

### ISSUE THREAD

**Issue by lq132069** [tadz-io/hydropt#5]
Your work is particularly meaningful. I am working on water quality inversion and currently have the spectral curves of water bodies. I want to obtain the absorption and scattering coefficients of the water bodies. Could you please explain how to use your code to input the given spectral curves of water bodies and output the absorption and scattering coefficients?

**Comment by tadz-io** [comment]
that's possible. The readme shows you how to invert your remote sensing reflectance (Rrs): https://github.com/tadz-io/hydropt 

Once you obtain your concentration estimates for you bio-optical components:
```python
# estimate parameters
xhat = inv_model.invert(y=rrs, x=x0)
```
 you can do this:

``` python
# get the concentration after inversion
# here i assume one of you components is named 'phytoplankton'

component_name = 'phytoplankton'
phyto = {component_name: xhat.params[component_name].value}
iops = bio_opt.get_iop(**phyto)
```

In `iops` you will have the absorption and backscatter coefficients for your specified wavelengths. Hope that helps.

**Comment by lq132069** [comment]
Thank you very much for your kindly help. Your response plays an essential role to my research work!

**Comment by tadz-io** [comment]
> Thank you very much for your kindly help. Your response plays an essential role to my research work!

your welcome. I consider the issue resolved and close the thread. In case you run into another problem just create another issue.
